### ISSUE TITLE
Additional checklist

### ISSUE THREAD

**Issue by blaggacao** [Mic92/nixpkgs-review#113]
https://github.com/Mic92/nixpkgs-review/blob/2661aaa1fbee70e5c3258ee9daf73bd40c9eba9b/nixpkgs_review/report.py#L124

Since this is posted on github, It would make sense to provide a default checklist of additional checks performed.
Although, arguably, if it's checklistable, it's also scriptable.

Hence, maybe provide a section for manual checks provided?
```md
Additional manual checks completed:
- [ ] Tested all binaries in `./results/bin`
- [ ] `grep WARN ./logs/*` empty
- [ ] `grep ERR ./logs/*` empty
```

The intent being the reviewer could either:
- complete the list locally `editor result.md`
- or tick the boxes on github

**Comment by blaggacao** [comment]
Result _could_ be something like: https://github.com/NixOS/nixpkgs/pull/78451#issuecomment-655088862

**Comment by blaggacao** [comment]
Superseded by #115
